import React from 'react';
import OverlayScrollbars from 'overlayscrollbars';

export default class Tut2 extends React.Component {
    constructor(props) {
        super(props);
    }

    async componentDidMount(){
        await(10);
        var osInstance = OverlayScrollbars(document.body);
        osInstance.scroll({ top : 0 });
    }

    render() {
        return (
            <div>
                <h1>Tut2</h1>
                <p>
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                    Incididunt anim ex sunt pariatur sint ipsum sit cupidatat pariatur. Officia proident nisi ut fugiat et ipsum in. Est irure id minim nisi ad ut nisi. Cillum exercitation minim non labore deserunt et proident sint ullamco Lorem. In aute velit sunt sit sint non voluptate deserunt labore. Sint pariatur labore consectetur occaecat veniam laboris cupidatat exercitation non et aliqua. Esse eu ipsum voluptate eu aliqua magna voluptate qui nulla ullamco.
                </p>
            </div>
        )
    }
}
